version: '3'
services:
  flask_app:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    environment:
      CSV_FILE_LOCATION: /path/to/local/csv/file.csv
      TARGET_COLUMN: "target_column_name"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
